[WEBSITE-759] Automated Browser testing
ukparliament/parliament.uk-awt pull request #1
Opened 2017-03-14 14:13 UTC by naseberry

2017-03-14 16:43 UTC, jakemulley requested changes

2017-03-14 16:43 UTC, jakemulley commented on Makefile
> +sauce:
This should be a .PHONY target (https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html)

2017-03-14 16:43 UTC, jakemulley commented on Makefile
> +isauce:
This should be a .PHONY target (https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html)

2017-03-14 16:43 UTC, jakemulley commented on Makefile
> +isauce:
It might also be better to give it a more meaningful name than `isauce`

2017-03-14 16:43 UTC, jakemulley commented on test/index.js
> +var fs = require('fs'),
Tabbing here does not follow the `.editorconfig` specification

2017-03-14 16:43 UTC, jakemulley commented on test/index.js
> +			'name': 'Mobile-iOS-safari-9',
Do we want to commit massive TODO comments?

2017-03-14 16:43 UTC, jakemulley commented on test/index.js
> +}
This might be better restructured to use Promises

2017-03-15 09:51 UTC, UsmanAfzal commented on test/index.js
> +}
Possibly. That would be better as another commit that can be reviewed to compare

2017-03-15 10:21 UTC, jakemulley approved these changes

2017-03-15 10:26 UTC, merged